version: 0.2

phases:
  pre_build:
    commands:
      - echo  build....
      - npm install
      - node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - IMAGE_TAG=`date +"%Y%m%d.%H%M%S"`
      - docker build -t angular .
      - docker tag angular:latest 090187438878.dkr.ecr.us-east-1.amazonaws.com/demo-pipeline-repo:$IMAGE_TAG
      - docker tag angular:latest 090187438878.dkr.ecr.us-east-1.amazonaws.com/demo-pipeline-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 090187438878.dkr.ecr.us-east-1.amazonaws.com/demo-pipeline-repo:$IMAGE_TAG
      - docker push 090187438878.dkr.ecr.us-east-1.amazonaws.com/demo-pipeline-repo:latest
      - aws codepipeline start-pipeline-execution --name deploy
